const SRC = 'src';
const MAIN = 'main';
const RESOURCES = 'resources';
const CONFIG = 'config';
const LIQUIBASE = 'liquibase';
const CHANGELOG = 'changelog';

const SRC_MAIN = `${SRC}/${MAIN}`;
const SRC_MAIN_RESOURCES = `${SRC_MAIN}/${RESOURCES}`;
const SRC_MAIN_RESOURCES_CONFIG = `${SRC_MAIN_RESOURCES}/${CONFIG}`;
const SRC_MAIN_RESOURCES_CONFIG_LIQUIBASE = `${SRC_MAIN_RESOURCES_CONFIG}/${LIQUIBASE}`;
const SRC_MAIN_RESOURCES_CONFIG_LIQUIBASE_CHANGELOG = `${SRC_MAIN_RESOURCES_CONFIG_LIQUIBASE}/${CHANGELOG}`;

module.exports = {
    SRC,
    MAIN,
    RESOURCES,
    CONFIG,
    LIQUIBASE,
    CHANGELOG,
    SRC_MAIN,
    SRC_MAIN_RESOURCES,
    SRC_MAIN_RESOURCES_CONFIG,
    SRC_MAIN_RESOURCES_CONFIG_LIQUIBASE,
    SRC_MAIN_RESOURCES_CONFIG_LIQUIBASE_CHANGELOG
};